name = "ShipMMG"
uuid = "37f2b0bf-0c13-4883-8808-e75eb56597e7"
authors = ["Taiga MITSUYUKI <mitsuyuki-taiga-my@ynu.ac.jp>"]
version = "0.0.3"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Dierckx = "0.5"
DifferentialEquations = "6.15"
ParameterizedFunctions = "5.6"
Parameters = "0.12"
Plots = "1.6"
Turing = "0.19"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
